Improvement: 单据处理手动节点表单更换插件
TencentBlueKing/bk-itsm pull request #902
Opened 2022-08-03 07:51 UTC by zyxazhang

2022-08-04 15:20 UTC, luofann requested changes

2022-08-04 15:20 UTC, luofann commented on frontend/pc/src/views/ticket/details/currentSteps/CurrentStepItem.vue
> +              </process-form-plugin>
这里使用lesscode表单的逻辑是，如果当前单据是来自于lesscode应用提单，则人工节点表单用lesscode表单插件渲染

2022-08-04 15:20 UTC, luofann commented on frontend/pc/.eslintignore
> +src/assets/jsflow.js
上面有个相同的

2022-08-04 15:20 UTC, luofann commented on frontend/pc/src/main.js
> -import router from "./router";
上面都是双引号，eslint没有报错吗

2022-08-04 15:20 UTC, luofann commented on frontend/pc/src/views/ticket/details/currentSteps/CurrentStepItem.vue
> +        debugger;
调试语句去掉

2022-08-04 15:20 UTC, luofann commented on frontend/pc/src/views/ticket/details/currentSteps/CurrentStepItem.vue
> +              }
如果使用lesscode表单，直接用v-model双向绑定可以取值

2022-11-15 02:40 UTC, tencentblueking-adm commented
[![CLA assistant check](https://bk-cla.bktencent.com:443/pull/badge/not_signed)](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-itsm?pullRequest=902) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-itsm?pullRequest=902) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bk-cla.bktencent.com:443/check/TencentBlueKing/bk-itsm?pullRequest=902) it.</sub>

2024-09-25 16:18 UTC, closed without merging